### ISSUE TITLE
Bad serialization when retrieving `Pricing` object

### ISSUE THREAD

**Issue by pgmarc** [Alex-GF/Pricing4TS#14]
When reading a Pricing2Yaml version 1.0 it dumps to the same file the newest version of the spec (2.0) with bad serialization.

Original file:
```yaml
saasName: PetClinic
version: '1.0'
day: 15
month: 1
year: 2024
currency: EUR
hasAnnualPayment: false
features:
  pets:
plans:
  BASIC:
  GOLD:
  PLATINUM:
addOns:
  havePetDashboards:
  smartClinicReports:
```

When retrieving `Pricing` object I get in the file this:
```yaml
saasName: PetClinic
version: '2.0'
createdAt: '2024-01-15'
currency: EUR
hasAnnualPayment: false
features:
 - name: pets
plans:
  - name: BASIC
  - name: GOLD
  - name: PLATINUM
addOns:
  - name: havePetsDashboard
  - name: smartClinicReports:
```
